# Generated by Django 6.0.3 on 2026-04-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_userblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="part_of_full_review",
            field=models.BooleanField(default=False),
        ),
    ]
